---

- name: Modipv6
  command: modprobe ipv6
  failed_when: false
  when: >
    not (ansible_virtualization_type is defined and 
    (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
    )

- name: Restart network
  service:
    name: network
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker") and
    not (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8)

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker") and
    ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8