---

- name: Deployment
  hosts: all
  tasks: 
  - name: Print some debug information 
    vars: 
      msg: |
          Ansible Distribution: {{ ansible_distribution }}
          Ansible Dist version: {{ ansible_distribution_version }}
          Ansible Dist family: {{ ansible_os_family }}
          Setup var: {{ setup }}
    debug: 
      msg: "{{ msg.split('\n') }}"       
    tags: debug_info



