---

- name: Print some debug information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Dist family: {{ ansible_os_family }}
        Setup var: {{ setup }}
  debug: 
    msg: "{{ msg.split('\n') }}"
  tags: debug_info


- name: Set default zabbix & iptables configuration file path
  set_fact:
    path_zabbix_config: "/etc/zabbix/zabbix_agent2.conf"
    path_iptables_config: "/etc/sysconfig/iptables"


- name: Set zabbix configuration file path for exception distribution 
  set_fact:
    path_zabbix_config: "/etc/zabbix/zabbix_agentd.conf"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "7")


########################## ROCKY ##########################

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/rhel/9/x86_64/zabbix-release-6.2-3.el9.noarch.rpm"
  when: (ansible_facts['distribution'] == "Rocky" and ansible_facts['distribution_major_version'] == "9")

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm"
     gpgkey: "https://repo.zabbix.com/zabbix-official-repo.key"
     when: (ansible_facts['distribution'] == "Rocky" and ansible_facts['distribution_major_version'] == "8")

########################## CENTOS ##########################

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm"
     gpgcheck: true
     gpgkey: "https://repo.zabbix.com/zabbix-official-repo.key"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8")

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.0/rhel/6/x86_64/zabbix-release-6.0-4.el6.noarch.rpm"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")

########################## DEBIAN ##########################

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian11_all.deb"
     path_zabbix_package: "/tmp/zabbix-agent2.deb"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "11")

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian10_all.deb"
     path_zabbix_package: "/tmp/zabbix-agent2.deb"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10")

- name: Set zabbix repo link {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  set_fact:
     path_zabbix_repo: "https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian9_all.deb"
     path_zabbix_package: "/tmp/zabbix-agent2.deb"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")

###########################################################

- name: Remove zabbix-agent package 
  package: 
    state: absent
    name: 
      - zabbix-agent
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] >= "6") or
        (ansible_facts['distribution'] == "Rocky" and ansible_facts['distribution_major_version'] == "8") or 
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] >= "9")


- name: Import the Zabbix GPG key
  rpm_key:
    state: present
    key: "{{ gpgkey }}"
  when: (ansible_facts['distribution'] == "Rocky" or "CentOS"  and ansible_facts['distribution_major_version'] == "8")


- name: Install zabbix-agent2 Redhat package from the internet
  yum:
    name: "{{ path_zabbix_repo }}"
    state: present
    validate_certs: no
  when: ansible_os_family == "RedHat"

#################### DEBIAN PART #####################
- name: Download zabbix-agent2 package
  get_url:
    url: "{{ path_zabbix_repo }}"
    dest: /tmp/zabbix-agent2.deb
    validate_certs: no
  when: ansible_os_family == "Debian"
  

- name: Install zabbix-agent2 package {{ ansible_distribution }}
  apt:
    deb: "{{ path_zabbix_package }}"
    state: present
  when: ansible_os_family == "Debian"
  
##################################################


- name: Installion zabbix-agent2 package 
  package: 
    state: present
    update_cache: true
    name:
      - zabbix-agent2


- name: Replace multiple lines and entries
  replace:
    path: "{{ path_zabbix_config }}"
    regexp: '^[\s]*{{ item.From }}\s*=.*$'
    replace: '{{ item.To }}'
  with_items:
    - { From: "Server", To: "Server={{ zabbix.internal_ip }}"}
    - { From: "Hostname", To: "Hostname={{ ansible_hostname }}"}


- name: Enable service zabbix-agent2
  service:
    name: zabbix-agent2
    enabled: yes
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] >= "6") or
        (ansible_facts['distribution'] == "Rocky" and ansible_facts['distribution_major_version'] == "8") or 
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] >= "9")

- name: Ansible Insert rules zabbix-agent in iptables
  blockinfile:
    path: "{{ path_iptables_config }}"
    block: |
      -A INPUT -p tcp --dport {{zabbix.port}} -s {{zabbix.internal_ip}} -d 0.0.0.0/0 -j ACCEPT
    insertbefore: -A INPUT -j REJECT --reject-with icmp-host-prohibited

- name: Restart service zabbix-agent2
  service:
    name: zabbix-agent2
    state: restarted
  when: setup is defined