---
#TODOO : Voir avec Alex pour trouver une forme générique de fichier iptables .
######## SETTING VARIABLES OF DIFFERENTS PATH FROM OS #######################
- name: Set iptables file path  for RedHat
  set_fact:
    path_iptables_config: "/etc/sysconfig/iptables"
  when: ansible_os_family == "RedHat"

- name: Set iptables file path  for Debian
  set_fact:
    path_iptables_config: "/etc/iptables/rules.v4"
  when: ansible_os_family == "Debian"

# We delete the generic iptables configuration file and load the one we have previously configured 
- name: Supprimer le fichier
  file: 
    path: "{{ path_iptables_config }}"
    state: absent

- name: Configure iptables
  iptables:
    state: file
    filename: "{{ iptables_file }}"
    with_items: "{{ iptables_rules }}"

- name:  Insert rules in iptables
  blockinfile:
    path: "{{ path_iptables_config }}"
    block: |
      -A INPUT -p tcp --dport {{zabbix.port}} -s {{zabbix.internal_ip}} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
    insertbefore: COMMIT