---



- name: Disable IPv6 with sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Sysctl timestamp ipv4-disable ipv6
  blockinfile:
    block: |
        net.ipv4.tcp_timestamps = 0
        net.ipv6.conf.default.disable_ipv6 = 1
        net.ipv6.conf.all.disable_ipv6 = 1
    path: /etc/sysctl.conf
    state: present

- name: Debian | blacklist ipv6 in modprobe
  lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    line: 'blacklist ipv6'
    mode: '0644'
    create: yes
  when: ansible_os_family == 'Debian'

- name: RedHat | placeholder true for ipv6 in modprobe
  lineinfile:
    dest: /etc/modprobe.conf
    line: 'install ipv6 /bin/true'
    mode: '0644'
    create: yes
  when: ansible_os_family == 'RedHat'

- name: RedHat | disable ipv6 in sysconfig/network
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: '0644'
    backup: yes
    create: yes
  with_items:
    - { regexp: 'NETWORKING_IPV6=.*', line: 'NETWORKING_IPV6=NO' }
    - { regexp: 'IPV6INIT=.*', line: 'IPV6INIT=no' }
  notify:
    - Restart network
    - Restart NetworkManager
  when: ansible_os_family == 'RedHat'


- name: Disable network ipv6 network
  blockinfile:
    block: |
      NETWORKING_IPV6=no
    path: /etc/sysconfig/network
    state: present
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: Disable network ipv6 eth0 centos 6
  blockinfile:
    block: |
      IPV6INIT="no"
    path: /etc/sysconfig/network-scripts/ifcfg-"{{ ansible_default_ipv4.interface }}"
    state: present
  ignore_errors: true
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Disable network ipv6 eth0 centos & rocky 7-8
  blockinfile:
    block: |
      IPV6INIT=no
    path: /etc/sysconfig/network-scripts/ifcfg-"{{ ansible_default_ipv4.interface }}"
    state: present
  ignore_errors: true
  when: ansible_distribution in ["CentOS", "Rocky"] and ansible_distribution_major_version >= "7"

- name: Disable network ipv6 eth0 centos & rocky 9
  blockinfile:
    block: |
      IPV6INIT=no
    path: /etc/NetworkManager/system-connections/{{ ansible_default_ipv4.interface }}.nmconnection
    state: present
  ignore_errors: true
  when: ansible_distribution in ["CentOS", "Rocky"] and ansible_distribution_major_version == "9"

- name: disables iptables6
  systemd:
    state: stopped
    name: iptables6
    enabled: no
  ignore_errors: true
  when: ansible_distribution in ["CentOS", "Rocky"] and ansible_distribution_major_version >= "7"