---


- name: Print some debug information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Dist family: {{ ansible_os_family }}
        location var: {{ location }}
  debug: 
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- include_tasks: "redhat.yml"
  when: (ansible_distribution == "Rocky" or ansible_distribution == "CentOS")

- include_tasks: "system.yml"
- include_tasks: "prompt.yml"
- include_tasks: "set-hostname.yml"

