---


- name: Install epel-release
  yum:
    name:
      - epel-release
      - xe-guest-utilities-latest



- name: Install let's encrypt Rocky 8 or major version
  yum:
    name:
      - certbot
      - python3-certbot-nginx
  when: (ansible_distribution == "Rocky" and ansible_distribution_major_version >= "8")


- name: Create letsencrypt directory
  file:
    path: /var/www/letsencrypt/
    state: directory
    owner: nginx
    mode: '0755'

- name: stop service nginx 
  service:
    name: nginx
    state: stopped
  when: setup is defined

# Execute this part if you don't have the path with the name of the variable 
- name: Request for ssl certificat {{ domain_le }} 
  shell: certbot certonly --standalone --non-interactive --agree-tos --no-eff-email -d {{ domain_le }} --register-unsafely-without-email
  when: (ansible_distribution == "Rocky" and ansible_distribution_major_version >= "8")
  ignore_errors: true


- name: Renew letsencrypt certificate
  cron:
    name: Renew letsencrypt certificate
    minute: "0"
    hour: "0"
    month: "*"
    job: "certbot renew --quiet && systemctl reload nginx"
  ignore_errors: true

- name: Insert content of mautic-conf template
  template:
    src: mautic.conf.j2
    dest: /etc/nginx/conf.d/mautic.conf
  ignore_errors: true

- name: Restart service nginx 
  service:
    name: nginx
    enabled: yes
    state: restarted
  when: setup is defined


