---

- name: Git checkout
  git:
    repo: https://github.com/mautic/mautic
    dest: /var/www/mautic
    version: 2.16.3

- name: Execute the composer command in /var/www/mautic
  shell: |
    export COMPOSER_ALLOW_SUPERUSER=1
    /usr/local/bin/composer self-update --1
    /usr/local/bin/composer install
    export COMPOSER_ALLOW_SUPERUSER=0
  args:
    chdir: /var/www/mautic

- name: Change file ownership /var/www/mautic
  file:
    path: "/var/www/mautic"
    recurse: yes
    owner: nginx
    group: nginx











