---

- name: Sending an e-mail using Gmail SMTP servers
  community.general.mail:
    host: smtp.telemaque.fr
    port: 587
    username: a.benchalal@telemaque.fr
    password: 4FbRU*>C606!
    to: ounihassen@tanis-tunisie.com
    subject: Ansible-test
    body: System {{ ansible_hostname }} has been successfully provisioned.
    secure: starttls

- name: Installation paquets mailx Centos et rocky
  yum:
    name:
      - mailx
    state: present
    ignore_errors: yes
  when: ansible_distribution in ["CentOS", "Rocky"] and ansible_distribution_major_version >= "7"
